### PR TITLE
Series of fixes to better follow the rules and accomodate global bonuses

### PR DESCRIPTION
**Pull request by Marcloure**
I made some changes on how resistances and weaknesses are calculated. It should now follow the official rules.

The way I did, it works as:
• if immune to all damage, it takes no damage
• else it will check each damage type and consider the lowest resistance
• if the lowest resistance is negative and there is a positive resist all (or vice-versa), the final resistance will be a sum of both

### CODE REVIEW

**Comment by Marcloure** [comment]
Sorry for my confusion trying to merge this one. I got a conflict and messed everything trying to revert it. Only the [this last commit](https://github.com/EndlesNights/dnd4eBeta/pull/98/commits/23f56b36c9192a632d1b5d80fa56992855ac5f02) actually makes any change.

**Comment by Marcloure** [comment]
So, this pull request became kinda huge. I'll try to summarize my commits here (from most oldest to newest):

1. I updated the weaknesses and resistances calculations to follow the rules. Via [23f56b3](https://github.com/EndlesNights/dnd4eBeta/pull/98/commits/23f56b36c9192a632d1b5d80fa56992855ac5f02)
2. I reordered the draw order so that Requirements and Trigger come before Target, since you need to know if you can use a power before actually target someone. Via [89644d9](https://github.com/EndlesNights/dnd4eBeta/pull/98/commits/89644d984938377aeabac2bab2aa91e0c7b2509a)
3. Hit text shows even if the power doesn't roll an attack. Via [8ddd312](https://github.com/EndlesNights/dnd4eBeta/pull/98/commits/8ddd312e941f0cac234486e8b997598e3e6db36d)
4. Powers can have an optional secondary power source. Via [a8dee3c](https://github.com/EndlesNights/dnd4eBeta/pull/98/commits/a8dee3c76299a5a58aa29049b0a5d75d704ce2c5)
5. Added an Attack and Damage Modifiers that can be used for feats and items that gives you a global bonus to attack or damage rolls. These can be used in formulas as `@atkMod` and `@dmgMod`, and come by default in powers. Via [bb610e7](https://github.com/EndlesNights/dnd4eBeta/pull/98/commits/bb610e7939b4721f1f7d46ebf3bb406b59c450f1)

**Comment by Marcloure** [comment]
This last commit fixes an oversight where 0 resistance would actually deal no damage.

**Comment by EndlesNights** [comment]
Just making one change for your solution to issue #90

Move Hit/Miss detail text into Effect Details area for Item Powers
See Wizard Sleep (PHB pg. 160)  as an example of a power with an attack roll, Hit/Miss details, but no damage. So I moved it all just to effects area.

**Pull request merged**
