### PR TITLE
Minor Fixes:

### PR DESCRIPTION
**Pull request by draconas1**
Consumable name and type are part of main item document not system collection, fixes "undefined undefined" when using consumables

Effects would not set for the first combatent because combat.turn = 0 === false when put in a truthy comparison check.  I actually managed to find this in a bizarre edgecase where the next line failed because combat.turn had been set, but there was no combatent in that part of the array so got an undefined.  Have not been able to replicate it, but made the check more paranoid.

Heal dialog menu now displays surge value.  (mostly useful for me because my players need to deal with mournland healing which halves the value)

changelog updated to fix spelling and fix mis-attributed changeset.

### CODE REVIEW

**Comment by draconas1** [comment]
Also an update to hooks.js to stop TAH throwing warnings, turns out I had already removed all the .data references there / used their helpers that have updated to v10, so it was only in our API hooks that there was a problem.

**Comment by draconas1** [comment]
And on a roll.  Fix for #241

**Comment by EndlesNights** [comment]
> mis-attributed changeset.
I'm sorry about that mistake. Must have had the wrong name on my clipboard. 
Anyway I'll take a look at these in in a bit, as I know there were some other minor fixes I wanted to take a look at as well.

**Comment by draconas1** [comment]
No worries mate, it happens.

**Pull request merged**
